language: python
python:
    - "3.8"
before_install:
    - pip install pytest pytest-cov
    - pip install codecov
    - pip install pandas
    - pip install matplotlib
    - pip install sklearn
    - pip install ase
    - pip install pymatgen
    - pip install rdkit-pypi
    - pip install torch
    - pip install torch_scatter
    - pip install torch-sparse
    - pip install torch-geometric
script:
    - pytest --cov=./
after_success:
        - bash <(curl -s https://codecov.io/bash)
