codecov:
  require_ci_to_pass: yes
  token: e4ce0139-cc7f-476b-a393-1a675838eab6

coverage:
  precision: 2
  round: down
  range: "70...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
