batch_size: 256
epochs: 100
eval_every_n_epochs: 1
fine_tune_from: None
log_every_n_steps: 50
weight_decay: 1e-6
init_lr: 0.001
gpu: cuda:0
data_name: fermi

model_type: gin
model: 
  num_layer: 5
  emb_dim: 128
  feat_dim: 256
  pool: mean
  drop_ratio: 0.0

# model_type: dimenet
# model: 
#   hidden_channels: 128
#   out_channels: 1
#   num_blocks: 6
#   num_bilinear: 8
#   num_spherical: 7
#   num_radial: 6
#   cutoff: 5.0
#   envelope_exponent: 5
#   num_before_skip: 1
#   num_after_skip: 2
#   num_output_layers: 3

dataset:
  num_workers: 0
  valid_size: 0.2
  data_dir: /home/rishikesh/Desktop/Schnet/data/Augmented_FE

