# frozen_string_literal: true

if Gem::Version.new(Bundler::VERSION) < Gem::Version.new('2.2.33')
  abort "Bundler version >= 1.3.5 is required"
end
source "https://rubygems.org"
gem 'github-pages', group: :jekyll_plugins

gemspec
